# Generated by Django 6.0.5 on 2026-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo for this session', null=True, upload_to='schedule_photos/'),
        ),
    ]
